### ISSUE TITLE
Use of non-standard suffixes causes compilation problems in clang and GCC.

### ISSUE THREAD

**Issue by Malkverbena** [GameNetworking/NetworkSynchronizer#139]
The suffixes used in your code don't seem to work with other compilers like GCC and clang.
You can use macros defined in <cstdint> or <limits>, such as INT8_MIN, INT8_MAX, UINT8_MAX, etc.

#include <climits>   // For integer limits
#include <cstdint>   // For fixed-width integer types

**Comment by AndreaCatania** [comment]
Hey, can you please link me the code that is causing the issue?

**Comment by Malkverbena** [comment]
The "namespace std" issue  can be solved just adding the headers.

The suffixes is a bit more complicated to solve.  
Basically the code uses suffixes like i8, i16, i32, i64, ui8, etc., on numeric constants. These suffixes are not part of the C++ standard and are specific to the MSVC compiler. If you are compiling the code with a different compiler like GCC or Clang, these suffixes will cause compilation errors.

**Comment by AndreaCatania** [comment]
Thanks! I'm not sure I understand what you mean about suffixes.
Can you please add the header to fix the std issue and then paste the new error?

**Comment by AndreaCatania** [comment]
Notice that you have to compile this library using C++20

**Comment by Malkverbena** [comment]
> Não sei onde no código que uso i32 como tipo. Você se refere a std::int32_t talvez? Se não, por favor, vincule aqui o código que está usando esses tipos e eu os refatorarei.

In this statement below the compiler understands this as a suffix.
#define NS__INT8_MIN (-127i8 - 1)

I understand that in MSVC this is just a number but other compilers understand it differently.

**Comment by Malkverbena** [comment]
As I said it`s possible solve it using something like:

`#include <cstdint>

#define NS__INT8_MIN INT8_MIN
#define NS__INT16_MIN INT16_MIN
#define NS__INT32_MIN INT32_MIN
#define NS__INT64_MIN INT64_MIN
`

But I don't know if suitable to your code.

**Comment by AndreaCatania** [comment]
I see what the problem is, I'll fix this shortly. Thanks a lot for pointing me to this.

**Comment by Malkverbena** [comment]
Taking a look on internet I just found a clue.
If you need to define literary values, try this to use standard suffixes like U for unsigned and LL for long long.(I just found out about this.)

```cpp
#define NS__INT8_MIN (-127 - 1)
#define NS__INT16_MIN (-32767 - 1)
#define NS__INT32_MIN (-2147483647 - 1)
#define NS__INT64_MIN (-9223372036854775807LL - 1)

#define NS__INT8_MAX 127
#define NS__INT16_MAX 32767
#define NS__INT32_MAX 2147483647
#define NS__INT64_MAX 9223372036854775807LL

#define NS__UINT8_MAX 0xFFU
#define NS__UINT16_MAX 0xFFFFU
#define NS__UINT32_MAX 0xFFFFFFFFU
#define NS__UINT64_MAX 0xFFFFFFFFFFFFFFFFULL
```

**Comment by AndreaCatania** [comment]
I've copied the Linux header and wrapped around a preprocessor define. Please let me know if it works now, if it doesn't I'll use the solution you just wrote here. https://github.com/GameNetworking/NetworkSynchronizer/commit/751b0b529fd6404d3df5f0f02db8be8208399175

**Comment by Malkverbena** [comment]
I don´t think itś a good ideia.
```cpp
#define NS__INT8_MIN (-127i8 - 1)
```
This will work only on MSVC. If you use another compiler it wont work even on windows.

**Comment by AndreaCatania** [comment]
I think you are correct and after a second consideration I've removed the NS__ macros to use the one provided by the header.

**Comment by Malkverbena** [comment]
This is good practice, but you can still use your own custom values ​​as long as they are in the universal C++ format.

**Comment by AndreaCatania** [comment]
Fixed
