### ISSUE TITLE
MIssiong hearders

### ISSUE THREAD

**Issue by Malkverbena** [GameNetworking/NetworkSynchronizer#140]
std::uint8_t, std::max and so on is not part of namespace std. on GCC and clang this is caousing erros.
the <cstdint> header must be included to work on other compilers.
If you would like, I could make a PR to fix this issue.

**Comment by AndreaCatania** [comment]
Hey, yes ofc, feel free to submit a PR to fix the problem. This lib is meant to be cross platform, if I've introduced a regression that prevents that, feel free to submit a fix.

**Comment by AndreaCatania** [comment]
Fixed by b87174aa8b7ddba7d4cf5a92a65b4b670b493947
